name: Homebrew cask tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cask:
    strategy:
      matrix:
        os: [macos-15-intel, macos-26]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Audit cask
        run: brew audit --cask --strict aethar01/gopdf/gopdf

      - name: Install cask
        run: brew install --cask aethar01/gopdf/gopdf

      - name: Verify app installation
        run: test -d "/Applications/GoPDF.app"

      - name: Uninstall cask
        run: brew uninstall --cask aethar01/gopdf/gopdf
